#!/usr/bin/env bash
# Multi-dataset (ATLAS + MoDEL) ESM2 mixed training
#
# Prerequisites:
#   1) Each dataset preprocessed into 100ps H5 (atlas_data_dir / model_data_dir)
#   2) split CSV: ATLAS columns [name, seqres]; MoDEL columns [name(=pdbids), seqres]
#      (MoDEL single-chain CSV generated by Datasets/MoDEL/prepare_MoDEL_singlechain.py)
#   3) Separate ESM2 pkl per dataset (key matches the split's name column)
#      -- MoDEL ESM2 must be computed from the seqres in the single-chain CSV, to stay aligned with trajectory/seqres
#
# Usage: bash scripts/run_train_multi_esm2.sh

set -euo pipefail
cd "$(dirname "$0")/.."
export PYTHONPATH="${PWD}:${PYTHONPATH:-}"

# ── Data paths (set to your actual paths) ──────────────────────────────────
ATLAS_H5="/path/to/data/Data/Atlas/atlas_100ps.h5"
MODEL_H5="/path/to/data/ProteinFlux_20260610/ProteinFlux_dev/Dataset/data_model_final_1393.h5"

ATLAS_TRAIN="/path/to/data/splits/atlas_train.csv"
ATLAS_VAL="/path/to/data/splits/atlas_val.csv"
MODEL_TRAIN="/path/to/data/ProteinFlux_20260610/ProteinFlux_dev/Dataset/model_train_1393.csv"
MODEL_VAL="/path/to/data/ProteinFlux_20260610/ProteinFlux_dev/Dataset/model_val_1393.csv"

# Separate ESM2 pkl per dataset (key=name column)
ATLAS_ESM="/path/to/data/esm2_t33_650m/atlas_esm2_embeddings.pkl"
MODEL_ESM="/path/to/data/ProteinFlux_20260610/ProteinFlux_dev/Dataset/model_esm2_t33_650m_1393.pkl"

# ── Mixed sampling & frame interval ────────────────────────────────────────
DATASET_WEIGHTS="{\"atlas\":0.5,\"model\":0.5}"          # per-dataset sampling weights
DATASET_FRAME_INTERVALS="{\"atlas\":1,\"model\":1}"      # H5 already 100ps → 1
MAX_RESAMPLE=100                                          # resample cap for short trajectory / missing ESM

# Assemble esm_paths (JSON)
ESM_PATHS="{\"atlas\":\"${ATLAS_ESM}\",\"model\":\"${MODEL_ESM}\"}"

# ── Run settings ────────────────────────────────────────────────────────────
GPU_IDS="0,1,2"
NUM_GPUS=3
RUN_NAME="esm2_multi_atlas_model1393"
MASTER_PORT=29512

# Optional: finetune from aa_emb / existing checkpoint (leave empty = from scratch)
CKPT="/path/to/data/ProteinFlux_20260610/ProteinFlux_dev/workdir/esm2_multi_atlas_model1393/checkpoints/backup-epoch=419-val_loss=0.3762.ckpt"

# ── ESM2 settings ───────────────────────────────────────────────────────────
ESM2_DIM=1280              # esm2_t33_650M_UR50D
ESM2_PROJ_DIM=512           # leave empty to use default (esm2_dim+embed_dim)//2

# ── Hyperparameters ───────────────────────────────────────────────────────────
EPOCHS=1000
BATCH_SIZE=1
LR=1e-4
MIN_LR=1e-6
WARMUP_EPOCHS=10
NUM_FRAMES=100
MAX_TRAIN_FRAMES=100       # first 10ns
CROP=256
NUM_WORKERS=4
GRAD_CLIP=1.0
ACCUMULATE_GRAD=1
PRECISION="32-true"

PRINT_FREQ=100
CKPT_FREQ=10
VAL_EPOCH_FREQ=1
EARLY_STOP_PATIENCE=400

# ── Optional args ───────────────────────────────────────────────────────────
CKPT_ARG=""
[ -n "${CKPT}" ] && CKPT_ARG="--ckpt ${CKPT}"
PROJ_DIM_ARG=""
[ -n "${ESM2_PROJ_DIM}" ] && PROJ_DIM_ARG="--esm2_proj_dim ${ESM2_PROJ_DIM}"

# ── Launch ──────────────────────────────────────────────────────────────────
CUDA_VISIBLE_DEVICES="${GPU_IDS}" torchrun --nproc_per_node "${NUM_GPUS}" --master_port "${MASTER_PORT}" \
    scripts/train.py \
    ${CKPT_ARG} \
    --run_name "${RUN_NAME}" \
    \
    --multi_dataset \
    --atlas_data_dir   "${ATLAS_H5}" \
    --model_data_dir   "${MODEL_H5}" \
    --atlas_train_split "${ATLAS_TRAIN}" \
    --atlas_val_split   "${ATLAS_VAL}" \
    --model_train_split "${MODEL_TRAIN}" \
    --model_val_split   "${MODEL_VAL}" \
    --dataset_weights         "${DATASET_WEIGHTS}" \
    --dataset_frame_intervals "${DATASET_FRAME_INTERVALS}" \
    --max_resample            "${MAX_RESAMPLE}" \
    --repeat 1 \
    \
    --esm_paths "${ESM_PATHS}" \
    --esm2_dim  "${ESM2_DIM}" \
    ${PROJ_DIM_ARG} \
    \
    --epochs          "${EPOCHS}" \
    --batch_size      "${BATCH_SIZE}" \
    --lr              "${LR}" \
    --min_lr          "${MIN_LR}" \
    --warmup_epochs   "${WARMUP_EPOCHS}" \
    --num_frames        "${NUM_FRAMES}" \
    --max_train_frames  "${MAX_TRAIN_FRAMES}" \
    --crop            "${CROP}" \
    --num_workers     "${NUM_WORKERS}" \
    --grad_clip       "${GRAD_CLIP}" \
    --accumulate_grad "${ACCUMULATE_GRAD}" \
    --precision       "${PRECISION}" \
    \
    --prepend_ipa \
    --ema \
    --adamW \
    \
    --print_freq          "${PRINT_FREQ}" \
    --ckpt_freq           "${CKPT_FREQ}" \
    --val_epoch_freq      "${VAL_EPOCH_FREQ}" \
    --early_stop_patience "${EARLY_STOP_PATIENCE}" \
    --resume

    # Optional: add ensemble distribution matching loss (smoke test first)
    #   --ensemble_loss --ensemble_kind energy --ensemble_feature per_residue \
    #   --ensemble_lambda 0.1 --ensemble_warmup 20 --ensemble_tau_min 0.3
    #
    # Note: in multi-dataset mode the DataModule uses the *_data_dir / *_train_split above,
    #       and no longer reads --data_dir / --train_split; ESM2 is enabled via --esm_paths.
